CREATE TABLE IF NOT EXISTS "demcodes_channel" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "demcodes_channel_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256) NOT NULL,
	"channel_id" varchar(256) NOT NULL,
	"subscription_verified" boolean DEFAULT false,
	"lease_seconds" integer,
	"subscription_expires_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT "demcodes_channel_channel_id_unique" UNIQUE("channel_id")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "demcodes_video" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "demcodes_video_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"video_id" varchar(256) NOT NULL,
	"channel_id" varchar(256) NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "demcodes_video_video_id_unique" UNIQUE("video_id")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "demcodes_change_event" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "demcodes_change_event_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"video_id" varchar(256) NOT NULL,
	"channel_id" varchar(256) NOT NULL,
	"event_timestamp" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "demcodes_video" ADD CONSTRAINT "demcodes_video_channel_id_demcodes_channel_channel_id_fk" FOREIGN KEY ("channel_id") REFERENCES "public"."demcodes_channel"("channel_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "demcodes_change_event" ADD CONSTRAINT "demcodes_change_event_video_id_demcodes_video_video_id_fk" FOREIGN KEY ("video_id") REFERENCES "public"."demcodes_video"("video_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "demcodes_change_event" ADD CONSTRAINT "demcodes_change_event_channel_id_demcodes_channel_channel_id_fk" FOREIGN KEY ("channel_id") REFERENCES "public"."demcodes_channel"("channel_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
